/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "resources.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_IMAGE_0  (GUI_ID_USER + 0x01)
#define ID_IMAGE_1  (GUI_ID_USER + 0x02)
#define ID_IMAGE_2  (GUI_ID_USER + 0x03)
#define ID_BUTTON_0  (GUI_ID_USER + 0x04)
#define ID_BUTTON_1  (GUI_ID_USER + 0x05)
#define ID_BUTTON_2  (GUI_ID_USER + 0x06)
#define ID_BUTTON_3  (GUI_ID_USER + 0x07)
#define ID_TEXT_0  (GUI_ID_USER + 0x08)


// USER START (Optionally insert additional defines)
U32 butterfly_status = 0;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 800, 480, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_1, 250, 200, 150, 150, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_2, 20, 20, 60, 32, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 40, 145, 40, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 40, 220, 40, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 40, 295, 40, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 40, 425, 40, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 400, 20, 340, 32, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
/* Home button callback example */
static void _cbButton_home(WM_MESSAGE * pMsg)
{
  /* Decode message type */
  switch (pMsg->MsgId)
  {
    /* Component repaint message */
    case WM_PAINT:
      GUI_DrawBitmap(&bmhome, 0, 0);
      break;
    /* Default callback message */
    default:
      BUTTON_Callback(pMsg);
  }
}

/* Mail button callback example */
static void _cbButton_mail(WM_MESSAGE * pMsg)
{
  /* Decode message type */
  switch (pMsg->MsgId)
  {
    /* Component repaint message */
    case WM_PAINT:
      GUI_DrawBitmap(&bmmail, 0, 0);
      break;
    /* Default callback message */
    default:
      BUTTON_Callback(pMsg);
  }
}

/* Butterfly button callback example */
static void _cbButton_butterfly(WM_MESSAGE * pMsg)
{
  /* Decode message type */
  switch (pMsg->MsgId)
  {
    /* Component repaint message */
    case WM_PAINT:
      GUI_DrawBitmap(&bmbutterfly, 0, 0);
      break;
    /* Default callback message */
    default:
      BUTTON_Callback(pMsg);
  }
}

/* Lang button callback example */
static void _cbButton_lang(WM_MESSAGE * pMsg)
{
  /* Decode message type */
  switch (pMsg->MsgId)
  {
    /* Component repaint message */
    case WM_PAINT:
      GUI_DrawBitmap(&bmlang, 0, 0);
      break;
    /* Default callback message */
    default:
      BUTTON_Callback(pMsg);
  }
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    // USER START (Optionally insert additional code for further widget initialization)
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    IMAGE_SetBitmap(hItem, &bmbackground); 	  	
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    IMAGE_SetBitmap(hItem, &bmbutterfly_blue);
    WM_MOTION_SetMoveable(hItem, WM_CF_MOTION_X | WM_CF_MOTION_Y, 1);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
    IMAGE_SetBitmap(hItem, &bmSTLogo);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    WM_SetCallback(hItem, _cbButton_mail);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    WM_SetCallback(hItem, _cbButton_home);
	  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    WM_SetCallback(hItem, _cbButton_butterfly);
	  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    WM_SetCallback(hItem, _cbButton_lang);

	
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Butterfly Demo");
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8080));
    
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)			  
        /* Move the butterfly */
        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
        IMAGE_SetBitmap(hItem, &bmbutterfly_blue);
        WM_MoveTo(hItem,250,200);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message
         if(butterfly_status == 0)
         {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1); IMAGE_SetBitmap(hItem, &bmbutterfly_yellow);butterfly_status = 1;
         }
         else if (butterfly_status == 1)
         {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);IMAGE_SetBitmap(hItem, &bmbutterfly_pink);butterfly_status = 2;
         }
         else if (butterfly_status == 2)
         {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);IMAGE_SetBitmap(hItem, &bmbutterfly_green);butterfly_status = 3;
         }
         else
         {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);IMAGE_SetBitmap(hItem, &bmbutterfly_blue);butterfly_status = 0;
         }
			
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  WM_Paint(hWin);
  WM_MOTION_Enable(1);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
