################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/assert.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/backdoor.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/boot.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/com.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/cop.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/file.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/net.c \
/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/xcp.c 

OBJS += \
./core/assert.o \
./core/backdoor.o \
./core/boot.o \
./core/com.o \
./core/cop.o \
./core/file.o \
./core/net.o \
./core/xcp.o 

C_DEPS += \
./core/assert.d \
./core/backdoor.d \
./core/boot.d \
./core/com.d \
./core/cop.d \
./core/file.d \
./core/net.d \
./core/xcp.d 


# Each subdirectory must supply rules for building sources it contributes
core/assert.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/assert.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/assert.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/backdoor.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/backdoor.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/backdoor.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/boot.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/boot.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/boot.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/com.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/com.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/com.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/cop.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/cop.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/cop.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/file.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/file.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/file.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/net.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/net.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/net.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
core/xcp.o: /Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/xcp.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"core/xcp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

