################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.c \
../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.c 

OBJS += \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.o \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.o 

C_DEPS += \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.d \
./lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.o: ../lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.c
	arm-none-eabi-gcc -c "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_FULL_LL_DRIVER '-D__weak=__attribute__((weak))' '-D__packed="__attribute__((__packed__))"' -DUSE_HAL_DRIVER -DSTM32F767xx -c -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/CMSIS/Device/ST/STM32F7xx/Include" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/STM32F7xx_HAL_Driver/Inc/Legacy" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/MainEngineBootloader/lib/uip" -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/uip -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/third_party/uip/apps/dhcpc -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM7_STM32F7 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"lib/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_utils.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

