################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/hooks.c \
../Core/Src/led.c \
../Core/Src/main.c \
../Core/Src/otm8009a.c \
../Core/Src/shared_params.c \
../Core/Src/stm32469i_discovery.c \
../Core/Src/stm32469i_discovery_lcd.c \
../Core/Src/stm32469i_discovery_sdram.c \
../Core/Src/stm32f4xx_hal_msp.c \
../Core/Src/stm32f4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32f4xx.c 

OBJS += \
./Core/Src/hooks.o \
./Core/Src/led.o \
./Core/Src/main.o \
./Core/Src/otm8009a.o \
./Core/Src/shared_params.o \
./Core/Src/stm32469i_discovery.o \
./Core/Src/stm32469i_discovery_lcd.o \
./Core/Src/stm32469i_discovery_sdram.o \
./Core/Src/stm32f4xx_hal_msp.o \
./Core/Src/stm32f4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32f4xx.o 

C_DEPS += \
./Core/Src/hooks.d \
./Core/Src/led.d \
./Core/Src/main.d \
./Core/Src/otm8009a.d \
./Core/Src/shared_params.d \
./Core/Src/stm32469i_discovery.d \
./Core/Src/stm32469i_discovery_lcd.d \
./Core/Src/stm32469i_discovery_sdram.d \
./Core/Src/stm32f4xx_hal_msp.d \
./Core/Src/stm32f4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32f4xx.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/hooks.o: ../Core/Src/hooks.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/hooks.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/led.o: ../Core/Src/led.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/led.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/otm8009a.o: ../Core/Src/otm8009a.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/otm8009a.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/shared_params.o: ../Core/Src/shared_params.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/shared_params.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32469i_discovery.o: ../Core/Src/stm32469i_discovery.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32469i_discovery.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32469i_discovery_lcd.o: ../Core/Src/stm32469i_discovery_lcd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32469i_discovery_lcd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32469i_discovery_sdram.o: ../Core/Src/stm32469i_discovery_sdram.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32469i_discovery_sdram.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_hal_msp.o: ../Core/Src/stm32f4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32f4xx_it.o: ../Core/Src/stm32f4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32f4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32f4xx.o: ../Core/Src/system_stm32f4xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -DUSE_FULL_LL_DRIVER -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source -I/Users/christiansager/klanghabitat_quantum/firmware/openblt_v011000/Target/Source/ARMCM4_STM32F4 -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Core/Src" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/Components" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/BSP/STM32469I-Discovery" -I"/Users/christiansager/klanghabitat_quantum/firmware/firmware quantum/DisplayBootloader/Fonts" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

