################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/BSP/stm32469i_discovery.c \
../Drivers/BSP/stm32469i_discovery_eeprom.c \
../Drivers/BSP/stm32469i_discovery_lcd.c \
../Drivers/BSP/stm32469i_discovery_qspi.c \
../Drivers/BSP/stm32469i_discovery_sdram.c \
../Drivers/BSP/stm32469i_discovery_ts.c 

OBJS += \
./Drivers/BSP/stm32469i_discovery.o \
./Drivers/BSP/stm32469i_discovery_eeprom.o \
./Drivers/BSP/stm32469i_discovery_lcd.o \
./Drivers/BSP/stm32469i_discovery_qspi.o \
./Drivers/BSP/stm32469i_discovery_sdram.o \
./Drivers/BSP/stm32469i_discovery_ts.o 

C_DEPS += \
./Drivers/BSP/stm32469i_discovery.d \
./Drivers/BSP/stm32469i_discovery_eeprom.d \
./Drivers/BSP/stm32469i_discovery_lcd.d \
./Drivers/BSP/stm32469i_discovery_qspi.d \
./Drivers/BSP/stm32469i_discovery_sdram.d \
./Drivers/BSP/stm32469i_discovery_ts.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/stm32469i_discovery.o: ../Drivers/BSP/stm32469i_discovery.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -c -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FatFs/src -I../Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/stm32469i_discovery.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/stm32469i_discovery_eeprom.o: ../Drivers/BSP/stm32469i_discovery_eeprom.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -c -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FatFs/src -I../Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/stm32469i_discovery_eeprom.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/stm32469i_discovery_lcd.o: ../Drivers/BSP/stm32469i_discovery_lcd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -c -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FatFs/src -I../Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/stm32469i_discovery_lcd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/stm32469i_discovery_qspi.o: ../Drivers/BSP/stm32469i_discovery_qspi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -c -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FatFs/src -I../Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/stm32469i_discovery_qspi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/stm32469i_discovery_sdram.o: ../Drivers/BSP/stm32469i_discovery_sdram.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -c -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FatFs/src -I../Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/stm32469i_discovery_sdram.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/stm32469i_discovery_ts.o: ../Drivers/BSP/stm32469i_discovery_ts.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DDEBUG -c -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FatFs/src -I../Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/CMSIS/Device/ST/STM32F4xx/Include -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I/Users/christiansager/STM32Cube/Repository/STM32Cube_FW_F4_V1.24.1/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/stm32469i_discovery_ts.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

